### ISSUE TITLE
How to save multiple svg's on a single page

### ISSUE THREAD

**Issue by nathanhere** [Hypercubed/svgsaver#2]
Is there a way to save multiple svg's that are on a single page?

**Comment by Hypercubed** [comment]
There is no built in way at the moment but you should be able to do this:

```
var svgs = document.querySelectorAll('svg');

Array.prototype.forEach.call(svgs, function(el) {
  svgsaver.asSvg(el);
});
```

However, your question lead me to discover a bug in FileSaver.js (https://github.com/eligrey/FileSaver.js/issues/165) so this will only work if you do not include FileSaver.

**Comment by Hypercubed** [comment]
If you need more help on this please reopen.  Thank you.
