### ISSUE TITLE
Example for PNG export

### ISSUE THREAD

**Issue by CountCount** [Hypercubed/svgsaver#3]
Can you provide an example of how to export PNGs?
In which browsers should this work?

**Comment by Hypercubed** [comment]
The example in this repo includes downloading as PNG.

code: https://github.com/Hypercubed/svgsaver/blob/master/demo/index.html
live: https://rawgit.com/Hypercubed/svgsaver/master/demo/index.html

You can see the compatibility chart here:  https://github.com/Hypercubed/svgsaver/wiki/Compatibility-Chart

**Comment by Hypercubed** [comment]
If I didn't answer you question please reopen... thanks.
