### ISSUE TITLE
Support for <use href="#somedefinition">?

### ISSUE THREAD

**Issue by devowhippit** [Hypercubed/svgsaver#4]
Hello, use tag references are not pulled into the exported SVG or PNG. Is there support for this?

**Comment by devowhippit** [comment]
I've ended up just cloning the definition and inserting it directly.

**Comment by Hypercubed** [comment]
Yes, you can add your own definitions.  If you think `use` should be added to the defaults I'd appreciate PR.

**Comment by xavierchow** [comment]
I came to the same issue, I have a svg marker with `<use href="#somedefinition">`, after digging into the code I found passing `{attrs: true}` to constructor works for me.

**Comment by Hypercubed** [comment]
PRs welcome.
